export enum ModalType {
    ADD_TASK = 'ADD_TASK',
    DELETE_TASK = 'DELETE_TASK',
    EDIT_TASK = 'EDIT_TASK',
    ADD_STICKER = 'ADD_STICKER',
    DELETE_STICKER = 'DELETE_STICKER',
    EDIT_STICKER = 'EDIT_STICKER',
  }